### ISSUE TITLE
Noob Question

### ISSUE THREAD

**Issue by arjuna-dev** [tonton81/SPISlave_T4#2]
Hi, I am confused about the usage of the library. For the TSPISlave library it is quite clear how to select the SPI pins:

```
uint8_t miso = 51;
uint8_t mosi = 52;
uint8_t sck = 53;
uint8_t cs = 43;
uint8_t spimode = 16;

TSPISlave mySPI = TSPISlave(SPI2, miso, mosi, sck, cs, spimode);
```

But for the SPISlave_T4 example  we don't find such code, instead only:

`SPISlave_T4<&SPI, SPI_8_BITS> mySPI;`

What am I missing?

**Comment by tonton81** [comment]
it uses the default SPI pins 10,11,12,13

**Comment by playaspec** [comment]
Will it select the right pins if you choose SPI1? That's Teensy4.1 pins 0, 1, 26, 27 for CS1, MISO1, MOSI1, and SCK1. Also, is the IRQ callback necessary? I'm driving two SPI ADCs simultaneous sampling. The main SPI drives the slave's _CS and SCK, and it's MOSI sends the same command to both ADCs. I want to manually read the slave when I handle reading the master. It looks like the ISR routine does some housekeeping. Ideally that would occur when I pop the value. The relevant bit of my code looks like this for context:

```
  SPI.beginTransaction(SPISettings(1000000, MSBFIRST, SPI_MODE0));
  uint32_t command = (0x00'06'00'00 | (channel <<10));
  Serial.print("Command: 0x");
  Serial.println(command, HEX);
  digitalWrite(CS_Pin, LOW);    // Enable the ADC
  mySPI.pushr(0xA5A5A5A5);   // Stuff a BS value into SPI1 TX so we can see if we need to swap pins
  vAdcVal[channel] = SPI.transfer32(command);         // Send read command for given channel
  cAdcVal[channel] = mySPI.popr();
  digitalWrite(CS_Pin, HIGH);   // Disable the ADC
  SPI.endTransaction();
```
